#!/Library/Frameworks/Python.framework/Versions/3.6/bin/python3
import argparse, sys, shlex

from fact_inject import windows, nix, parse


class FactInject:
    def __init__(self):
        parser = argparse.ArgumentParser(
            description='Add facts to multiple nodes at once',
            usage='''inject.py <command> -h [<hosts>] -j [<fact_file.json>]
        Inject commands:
           win    Inject Facter facts on a windows host.
           nix    Inject Facter facts on a *nix host.
        ''')
        parser.add_argument('command', help='Subcommand to run')
        # parse_args defaults to [1:] for args, but you need to
        # exclude the rest of the args too, or validation will fail
        args = parser.parse_args(sys.argv[1:2])
        if not hasattr(self, args.command):
            print('Unrecognized command')
            parser.print_help()
            exit(1)
        # use dispatch pattern to invoke method with same name
        getattr(self, args.command)()

    def win(self):
        parser = argparse.ArgumentParser(
            description='Facter for Windows')
        # NOT prefixing the argument with -- means it's not optional
        parser.add_argument('--host', help='The Windows host that facts will be added to')
        parser.add_argument('--file', help='JSON file containing facts to be added to the host')
        # Parse the args and inject the facts.
        args = parser.parse_args(sys.argv[2:])
        obj = parse.parse_input(args.file)
        facts = parse.convert_to_fact(obj)
        vars = windows.create_win_facter_vars(facts)
        print(vars)
        # hosts = shlex.split(args.host)
        #for host in hosts:
        #    print(host)
        #    nix.inject_facts(facts, host=host, username='vagrant', password='Heidim2015')
        #print(facts)

    def nix(self):
        parser = argparse.ArgumentParser(
            description='Facter for Linux'
        )
        parser.add_argument('--host', help='The Linux host that facts will be added to')
        parser.add_argument('--file', help='JSON file containing facts to be added to the host')
        # Parse the args and inject the facts.
        args = parser.parse_args(sys.argv[2:])
        obj = parse.parse_input(args.file)
        facts = parse.convert_to_fact(obj)
        hosts = shlex.split(args.host)
        for host in hosts:
            print(host)
            nix.inject_facts(facts, host=host, username='vagrant', password='Heidim2015')
        print(facts)

if __name__ == '__main__':
    FactInject()